export default [
  {
    // ! Warlord
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Hammer Flurry',
    dmgtype: 'physical',
    dps: [],
    range: 3,
    cooldown: 0,
    resource: 15,
    aoe: '3m frontal cone',
    description:
      'You perform a series of strikes with you hammer, damaging foes in front of you',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap (3 skills in combo)',
    details: [
      '1st skill: You inflict 50 physical damage on maximum 5 enemy targets in front of you',
      '2nd skill: You inflict 50 physical damage on maximum 5 enemy targets in front of you',
      '3rd skill: You inflict 2 hits 30 and 100 physical damage and a debuff Slow by 30% for 5 seconds on maximum 5 enemy targets in front of you',
      'The skill can be cast while moving',
    ],
    mechanics: ['5f9f3adcd706d724a4ecc093'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shield Block',
    dmgtype: 'physical',
    dps: [190],
    range: 0,
    cooldown: 0.5,
    resource: -10,
    aoe: 'character',
    description: 'You cover yourself using shield to block enemy attacks',
    type: 'Buff / Melee attack',
    usage:
      'Block: Skill hold (moment of enemy attack) Shield Counter: (Successful block) C key tap',
    details: [
      'Each successful block additionally consumes 10 willpower (willpower is consumed only once per 0.2 seconds)',
      'While blocking you are inflicted with a negative effect, decreasing your movement speed by 50%',
      'While blocking you are granted with an effect, decreasing incoming damage by 20% additionally to the main blocking effect',
      'While blocking you are granted with an effect, giving immunity to any negative mechanics like debuffs or any crowd control mechanics',
      'Upon successful block you can perform an additional skill Shield Counter within 5 seconds (skill cooldown 8 seconds)',
      'Shield Counter: you inflict 228 physical damage and debuff Stun for 2.5 seconds on maximum 5 enemy targets in front of you',
      'Upon inflicting damage with Shield Counter you restore 100 willpower',
    ],
    mechanics: [],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Whirlwind',
    dmgtype: 'physical',
    dps: [271],
    range: 4,
    cooldown: 10,
    resource: -135,
    aoe: '3m radius around the caster',
    description:
      'You perform a whirl attack, damaging foes around you with your hammer',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You inflict 95 physical damage for each 0.35 seconds for 3.5 seconds on maximum 7 enemy targets in radius',
      'While casting you are granted with an effect, giving immunity to control mechanics Knockback, Stagger and Tether',
    ],
    mechanics: ['5f9f3f2cd337f509b0b44dec'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Stomp',
    dmgtype: 'physical',
    dps: [82],
    range: 6,
    cooldown: 21,
    resource: 100,
    aoe: '2m radius around the caster',
    description:
      'You stomp the ground with your feet, damaging and pulling enemies around you',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You inflict 74 physical damage, a debuff Concussion for 5 seconds and a control Tether on maximum 7 enemy targets in the radius',
      'Concussion: incoming physical damage is increased by 40%. Upon hit the debuff is removed',
      'While casting you are granted with an effect, giving immunity to control mechanics Knockback, Stagger and Tether',
    ],
    mechanics: ['5f9f3bbbaeed841f349dacee', '5f9f3ed29b092903302dbb8f'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Battering Shield',
    dmgtype: 'physical',
    dps: [164, 164, 164],
    range: 3,
    cooldown: 8,
    resource: -60,
    aoe: '3x4m',
    description: 'You perform a series of shield strikes',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap (3 skills in combo)',
    details: [
      'The skill is represented by a series of consecutive shield strikes',
      '1st skill: You strike using your shield, inflicting 66 physical damage and control Stagger on maximum 5 enemy target within 3m range ahead',
      '2nd skill: You strike using your shield, inflicting 82 physical damage and control Stagger on maximum 5 enemy target within 3m range ahead',
      '3rd skill: You strike using your shield, inflicting 164 physical damage and control Knockdown on maximum 5 enemy target within 6m range ahead',
      'The skill ignores mechanics such as Dodge, Block, Invulnerability (though does not ignore effect Shield)',
    ],
    mechanics: ['5f9f3ebf9b092903302dbb8c'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shield Slam',
    dmgtype: 'physical',
    dps: [230],
    range: 6,
    cooldown: 15,
    resource: -60,
    aoe: '4x6m',
    description:
      'You slam your shield to the ground, creating ground explosions in front of you',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You perform a ground slam using your shield, creating two explosions, each inflicting 173 physical damage and control Airborne on maximum 7 enemy targets within maximum 6m range of the character',
      'If enemy is standing in the area of explosions overlapping they suffer both explosion hits',
      'While casting you are granted with an effect, giving immunity to control mechanics Knockback, Stagger and Tether',
    ],
    mechanics: ['5f9f3eb39b092903302dbb8b'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shield Charge',
    dmgtype: 'physical',
    dps: [48],
    range: 12,
    cooldown: 12,
    resource: 100,
    aoe: '1m radius around the target',
    description:
      'You perform a charge to a designated target, attacking them with your shield',
    type: 'Melee attack',
    usage: 'Crosshair aiming → Aim maintaining → Skill tap',
    details: [
      'You perform a charge with your shield, inflicting 43 physical damage and debuff Stun for 1 second on maximum 3 enemies within 1m radius around the skill target',
      'The skill cannot be used while in states of mechanics, preventing character movement',
      'The character is granted with an effect, giving immunity to mechanics of character control while casting the skill',
    ],
    mechanics: ['5f9f3575bac32b2e006a65d6', '5f9f3affd706d724a4ecc097'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Leap Slam',
    dmgtype: 'physical',
    dps: [146],
    range: 21,
    cooldown: 18,
    resource: -60,
    aoe: '4m radius',
    description: 'You perform a leap, slamming the ground with your hammer',
    type: 'AOE attack',
    usage: 'Skill tap → Area designation → Skill tap (or LMB tap)',
    details: [
      'You perform a leap to a designated area, inflicting 176 physical damage and debuff Stun for 3 seconds on maximum 7 enemy targets within radius',
      'The skill cannot be used while in states of mechanics, preventing character movement',
      'The character is granted with an effect, giving immunity to mechanics of character immobility while casting the skill',
    ],
    mechanics: ['5f9f3affd706d724a4ecc097'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Earth Splitter',
    dmgtype: 'fire',
    dps: [220],
    range: 18,
    cooldown: 18,
    resource: -60,
    aoe: '1x18m',
    description:
      'You launch a fire wave with your hammer on enemies in front of you',
    type: 'Piercing Projectile',
    usage: 'Crosshair aiming → Skill tap',
    details: [
      'You launch a fire wave that flies through, inflicting 296 fire magic damage on maximum 7 enemy targets on its path',
      'The skill has 100% critical hit chance so it always deals critical damage',
    ],
    mechanics: [],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shield Throw',
    dmgtype: 'physical',
    dps: [186],
    range: 18,
    cooldown: 0,
    resource: -50,
    aoe: '2m radius',
    description: 'You throw your shield to attack your enemies',
    type: 'Non-Piercing Projectile / Piercing Projectile',
    usage: 'Crosshair aiming → Skill tap',
    details: [
      'You throw a shield using your reticule, inflicting 84 physical damage on maximum 5 enemy targets within radius of hit. After that the shield flies back to the character',
      'While flying back the shield inflicts 84 physical damage on maximum 5 enemy targets on its path',
      'Upon hit the skill also inflicts a debuff Slow by 30% for 3 seconds on enemy targets',
      'The skill can be cast while moving',
    ],
    mechanics: ['5f9f3adcd706d724a4ecc093'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Pain Absorption',
    dmgtype: 'physical',
    dps: [60, -360],
    range: 0,
    cooldown: 0,
    resource: -10, //(per second)
    aoe: '2 ~ 12m radius',
    description:
      'You cover yourself with a shield, absorbing enemy damage to release it in a burst of energy',
    type: 'Buff / Melee attack',
    usage: 'Skill hold → Confirming targets within range → Skill release',
    details: [
      'During the skill cast you acquire an effect Block',
      'Each successful block additionally consumes 10 willpower (willpower is consumed only once per 0.2 seconds)',
      'While blocking you are granted with an effect, decreasing incoming damage by 20% additionally to the main blocking effect',
      'Upon successful block you can perform an additional skill Shield Counter within 5 seconds (skill cooldown 8 seconds)',
      'Shield Counter: you inflict 228 physical damage and debuff Stun for 2.5 seconds on maximum 5 enemy targets in front of you',
      'Each successful block additionally grants you with a stack of an effect Anger (maximum 5 stacks)',
      'Upon finishing the cast or cast cancel the explosion occurs around the caster. The parameters for the explosion depend on stacks of effect Rage gained',
      'Pain Absorption: Anger Release',
      '0 stacks: inflicts 102 physical damage and control Stagger on maximum 7 enemy targets within 3m radius',
      '1 stack: inflicts 153 physical damage and control Stagger on maximum 7 enemy targets within 3m radius',
      '2 stacks: inflicts 229 physical damage and control Stagger on maximum 7 enemy targets within 4m radius',
      '3 stacks: inflicts 305 physical damage and control Stagger on maximum 7 enemy targets within 6m radius',
      '4 stacks: inflicts 382 physical damage and control Knockdown on maximum 7 enemy targets within 8m radius',
      '5 stacks: inflicts 458 physical damage and control Airborne on maximum 7 enemy targets within 12m radius',
    ],
    mechanics: [
      '5f9f5f91ced5282c683237a4',
      '5f9f3ef79b092903302dbb92',
      '5f9f3f2cd337f509b0b44dec',
      '5f9f3ebf9b092903302dbb8c',
      '5f9f3eb39b092903302dbb8b',
    ],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shield Rush',
    dmgtype: 'physical',
    dps: [82],
    range: 10,
    cooldown: 15,
    resource: 10,
    aoe: '1x2m',
    description: 'You rush forward using your shield',
    type: 'Melee attack',
    usage: 'Directional aiming → Skill tap',
    details: [
      'You rush with your shield, inflicting a total 11 hits 21 physical damage each as well as control Knockback on maximum 5 enemy targets on your path',
      'During the skill cast you acquire an effect Block',
    ],
    mechanics: ['5f9f3ec59b092903302dbb8d', '5f9f5f91ced5282c683237a4'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Hammer Throw',
    dmgtype: 'physical',
    dps: [236],
    range: 18,
    cooldown: 15,
    resource: -40,
    aoe: '1m radius',
    description: 'You throw a hammer to attack your enemies',
    type: 'Non-Piercing Projectile',
    usage: 'Crosshair aiming → Skill tap',
    details: [
      'You throw your hammer, inflicting 213 physical damage and control Knockdown on maximum 5 enemy targets within radius of the hit',
    ],
    mechanics: ['5f9f3ebf9b092903302dbb8c'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Hammer Crush',
    dmgtype: 'physical',
    dps: [180, 225, 225, 225, 250],
    range: 2,
    cooldown: 15,
    resource: 0,
    aoe: '2 ~ 3m',
    description: 'You perform a series of crushing hammer attacks',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap (5 skills in combo)',
    details: [
      'The skill is represented by a series of 5 hammer attacks',
      '1 to 4 skills in the series: You inflict 180 physical damage on maximum 7 enemy targets within 2m radius area in front of you',
      '5th skill: You inflict 275 physical damage and control Knockdown on maximum 7 enemy targets within 3m radius area in front of you. You lose stacks of effect Berserk upon cast',
      'Each time you perform skills 1 to 4 you are granted with a stack of the effect Berserk, increasing your movement speed and attack speed by 20% (maximum 6 stacks)',
      'While casting you are granted with an effect, giving immunity to any negative mechanics like debuffs or any crowd control mechanics',
    ],
    mechanics: [
      '5f9f3575bac32b2e006a65d6',
      '5f9f369a76d3ea2af46a14bf',
      '5f9f3ebf9b092903302dbb8c',
      '5f9f60293c961106bce7e275',
      '5f9f3f2cd337f509b0b44dec',
    ],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Execution',
    dmgtype: 'physical',
    dps: [200, -1000],
    range: 5,
    cooldown: 15,
    resource: 0,
    aoe: 'An area with 3m radius in front of the caster',
    description:
      'You perform a strike, inflicting damage dependant on the enemy HP',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You perform a strike, inflicting 200 physical damage on maximum 7 enemy targets in an area in front of you',
      'The lower the amount of HP enemy has left, the more damage the skill does, up to 500%',
      'Damage does not disperse while hitting multiple targets',
      'While casting you are granted with an effect, giving immunity to control mechanics Knockback, Stagger and Tether',
    ],
    mechanics: ['5f9f6921f591a702100e836b', '5f9f3f2cd337f509b0b44dec'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Chain Hook',
    dmgtype: 'physical',
    dps: [94],
    range: 18,
    cooldown: 15,
    resource: 0,
    aoe: 'target',
    description: 'You use a chain to pull enemies to you',
    type: 'Melee attack',
    usage: 'Skill tap → Crosshair aiming → Skill tap',
    details: [
      'You select up to 5 targets to pull them with chains',
      'The skill inflicts 104 physical damage, control Tether and debuff Stun for 2 seconds',
    ],
    mechanics: ['5f9f3ed29b092903302dbb8f', '5f9f3affd706d724a4ecc097'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Defensive Strikes',
    dmgtype: 'physical',
    dps: [107, 122],
    range: 3,
    cooldown: 0,
    resource: 35,
    aoe: '2x3m',
    description:
      'You perform a series of shield strikes while maintaining a defensive posture',
    type: 'Buff / Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'The skill is represented by a series of 2 consecutive strikes',
      '1st skill: You inflict 75 physical damage on maximum 5 enemy targets, additionally inflicting control Stagger on them with a 25% chance',
      '2nd skill: You inflict 135 physical damage on maximum 5 enemy targets, additionally inflicting control Stagger on them with a 25% chance',
      'The skill ignores mechanics such as Dodge, Block, Invulnerability (though does not ignore effect Shield)',
    ],
    mechanics: ['5f9f3dfb0bb31a1cd4e84d44', '5f9f5f91ced5282c683237a4'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Charging Blitz',
    dmgtype: 'physical',
    dps: [226],
    range: 20,
    cooldown: 24,
    resource: 0,
    aoe: '4x20m',
    description: 'You charge your hammer to perform a sweeping strike',
    type: 'Melee attack',
    usage: 'Direction aiming → Skill hold → Skill release',
    details: [
      'The skill has 3 stages of charging influencing its power',
      '1st stage: You perform a 10m forward charge, inflicting 189 physical damage and control Airborne on maximum 7 enemy targets',
      'nd stage: You perform a 15m forward charge, inflicting 265 physical damage and control Airborne on maximum 7 enemy targets',
      '3rd stage: You perform a 20m forward charge, inflicting 360 physical damage and control Airborne on maximum 7 enemy targets',
    ],
    mechanics: ['5f9f3eb39b092903302dbb8b'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shred',
    dmgtype: 'physical',
    dps: [18],
    range: 3,
    cooldown: 5,
    resource: 0,
    aoe: 'Frontal cone with 3m radius',
    description:
      'You inflict bleeding wounds striking enemies with your hammer',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You perform a strike, inflicting 30 physical damage on maximum 5 enemy targets in front of you',
      'Skill hit additionally inflicts a stack of a debuff on enemy targets for 12 seconds, each 2 seconds dealing 40 physical damage (maximum 3 stacks)',
      '100% of damage inflicted (including debuff damage) heals the caster',
    ],
    mechanics: ['5f9f603b3c961106bce7e276', '5f9f3ce7031b621cfcedb73b'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Taunt',
    dmgtype: 'physical',
    dps: [],
    range: 18,
    cooldown: 20,
    resource: 50,
    aoe: '18m radius',
    description: 'You provoke enemies to attack you',
    type: 'AOE Debuff',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You raise the parameter of aggression towards you for maximum 7 enemy targets around you',
      'The skill inflicts a debuff Taunt on enemy targets for 8 seconds',
      'Taunt: Force enemies to attack you',
    ],
    mechanics: ['5f9f3d340bb31a1cd4e84d42'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Warcry',
    dmgtype: 'physical',
    dps: [],
    range: 0,
    cooldown: 40,
    resource: 0,
    aoe: 'Character',
    description: 'You shout to gain additional strength',
    type: 'Melee attack',
    usage: 'Skill Tap',
    details: [
      'You perform a shout, gaining a buff for 8 seconds, increasing your maximum HP by 20% and granting you immunity to control mechanics',
    ],
    mechanics: ['5f9f39e6a9f30514b00b5dcb', '5f9f3f2cd337f509b0b44dec'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Hammer Frenzy',
    dmgtype: 'physical',
    dps: [309, -517],
    range: 2,
    cooldown: 0,
    resource: -15,
    aoe: '3m radius',
    description:
      'You perform strikes with your hammers, accelerating attack speed with each next hit',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill hold',
    details: [
      'While holding the skill you perform strikes on area in 2m range in front of you, inflicting 202 physical damage on maximum 7 enemy targets within 3m radius',
      'While casting you are granted with an effect, giving immunity to control mechanics Knockback, Stagger and Tether',
    ],
    mechanics: ['5f9f369a76d3ea2af46a14bf'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Sacred Shield',
    dmgtype: 'light',
    dps: [100],
    range: 4,
    cooldown: 60,
    resource: 0,
    aoe: '5m radius',
    description:
      'You strike the ground with your shield, inflicting damage to enemies as well as granting buffs to allies',
    type: 'Melee attack, Buff, Summon',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'Upon casting you inflict 100 light magic damage on maximum 7 enemy targets in 5m radius, and then inflicting 9 hits 20 light magic damage each for each 0.5 seconds',
      'After, you inflict 300 light magic damage and control Airborne on maximum 7 enemy targets in 5m radius, at the same time granting a buff Sacred Shield for 10 seconds to allies within the same range',
      'Sacred Shield: Output damage, movement speed and attack speed is increased by 20%. Character is immune to state of control mechanics',
    ],
    mechanics: ['5f9f60473c961106bce7e277', '5f9f3eb39b092903302dbb8b'],
  },
  {
    archetype: '5f9f616c6ff4c0271c0f8885',
    name: 'Shield Bash',
    dmgtype: 'physical',
    dps: [177],
    range: 3,
    cooldown: 8,
    resource: 0,
    aoe: '2x3m',
    description:
      'You perform a powerful blow with your shield on enemies in front of you',
    type: 'Melee attack',
    usage: 'Melee distance approach → Skill tap',
    details: [
      'You perform a blow, inflicting 124 physical damage and debuff Stun on maximum 5 enemy targets in front of you',
      'At the same time you inflict a stack of a debuff Armor Crack for 20 seconds on enemy targets',
      'Armor Crack: incoming physical damage is increased by 10% (maximum 3 stacks)',
    ],
    mechanics: ['5f9f3c66a4418d2e0c53ece0', '5f9f3affd706d724a4ecc097'],
  },

  // ! GUNSLINGER
  {
    beid: '119',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Main Caliber',
    dmgtype: 'physical',
    dps: [0],
    range: 0,
    cooldown: 15,
    resource: -100,
    aoe: 'character',
    description: 'You load your weapons with special ammo',
    type: 'buff',
    usage: 'Skill tap',
    details: [
      'You get the buff, strengthening your output damage',
      'the buff increases all of your damage done by 15% for 7 seconds. Certain skills acquire special bonuses while the buff is active',
    ],
    mechanics: ['damage increase'],
  },
  {
    beid: '120',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Pistol Shot',
    dmgtype: 'physical',
    dps: [63],
    range: 18,
    cooldown: 0,
    resource: 8,
    aoe: 'target',
    description: 'You fire single rounds using your pistol',
    type: 'Dual Pistols, Channeling Target Projectile',
    usage: 'Crosshair aiming → Aim maintaining → Skill hold for channeling',
    details: [
      'You fire shots in a single target',
      'Each shot inflicts 21 physical damage',
    ],
    mechanics: [],
  },
  {
    beid: '121',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Multishot',
    dmgtype: 'physical',
    dps: [155],
    range: 18,
    cooldown: 0,
    resource: -8,
    aoe: 'target',
    description:
      'You prepare a special technique, allowing you to fire shot for multiple targets in the frontal cone, using your dual pistols',
    type: 'Dual Pistols, Channeling Target Projectile',
    usage: 'Crosshair aiming → Aim maintaining → Skill hold for channeling',
    details: [
      'You fire rounds in front of you, inflicting maximum 5 targets each with 29 physical damage',
      'Each enemy continuously taking damage acquire debuff Slow by 50%',
      'Damage does not disperse while hitting multiple targets',
      'You cannot automatically acquire ammo while channeling the skill',
    ],
    mechanics: ['slow'],
  },
  {
    beid: '122',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Rifle Shot',
    dmgtype: 'physical',
    dps: [51],
    range: 18,
    cooldown: 0,
    resource: 20,
    aoe: 'target',
    description: 'You aim to shoot your enemy with rifle precision bullet',
    type: 'Rifle, Non-Piercing Projectile',
    usage: 'Crosshair aiming → Aim maintaining → Skill hold for channeling',
    details: [
      'You fire your rifle, inflicting 64 physical damage and acquiring the stacking buff Shot Adjustment',
      'Shot Adjustment: increases critical hit chance for rifle skills by 2% stack (maximum 10 stacks)',
    ],
    mechanics: [],
  },
  {
    beid: '123',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Rocket',
    dmgtype: 'physical',
    dps: [197],
    range: 24,
    cooldown: 0,
    resource: -50,
    aoe: '2m radius',
    description: 'You fire your rifle with an explosive rocket shell',
    type: 'Rifle, Non-Piercing Projectile',
    usage: 'Skill tap → Aiming',
    details: [
      'You fire the rocket with the ballistic trajectory',
      'The rocket inflicts 178 and control Stagger to 5 targets maximum in the 2m radius',
    ],
    mechanics: ['stagger'],
  },
  {
    beid: '124',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Akimbo',
    dmgtype: 'physical',
    dps: [205],
    range: 18,
    cooldown: 0,
    resource: -15,
    aoe: '3m radius',
    description:
      'You turn your dual pistols into pair of shotguns to fire powerful explosive shells',
    type: 'Rifle, Non-Piercing Projectile',
    usage: 'Skill hold for channelling → Aiming',
    details: [
      'You fire explosive shells, inflicting 118 physical damage to 7 targets maximum in 3m radius',
      'You also inflict targets with debuff Slow by 50% for 1 second',
    ],
    mechanics: ['slow'],
  },
  {
    beid: '125',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Salto',
    dmgtype: 'physical',
    dps: [129],
    range: 16,
    cooldown: 0,
    resource: -100,
    aoe: '4m radius',
    description:
      'You make a jump and shooting enemies on your path while 5f9f3eb39b092903302dbb8b',
    type: 'Dual Pistols, AOE attack',
    usage: 'Directional control hold → Skill tap',
    details: [
      'You make a jump towards the designated direction for the 16m range. During the jump you acquire effect Dodge',
      'During the jump you fire 3 shot on your path, each shot inflicting 52 physical damage to 7 targets maximum in 4m radius',
      'Despite the mechanics section of the tooltips state the existence of the Movement Speed buff it is not specified in details on when you acquire it and for what period of time.',
    ],
    mechanics: ['dodge', 'movement speed increase'],
  },
  {
    beid: '126',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Summon Drones',
    dmgtype: 'physical',
    dps: [100],
    range: 0,
    cooldown: 24,
    resource: 0,
    aoe: '-',
    description: 'You make a jump, summoning 2 spheric robots',
    type: 'Summon',
    usage: 'Directional control hold → Skill tap',
    details: [
      'You make a jump towards the designated direction for 10m range and summon 2 drone, each existing for 15 seconds',
      'Drones fire at enemies in the area, inflicting 100 physical damage per shot to 3 targets maximum',
      'Drones cannot be affected by targeting skills and can only be damage by skills with AOE capabilities',
      'Drones inherits level and stats of the caster',
      'It is important to mention that drones have their own area of shooting enemies, but it is not specified in the tooltip nor is it visually shown',
    ],
    mechanics: [],
  },
  {
    beid: '127',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Summon Turret',
    dmgtype: 'physical',
    dps: [152, 134],
    range: 21,
    cooldown: 30,
    resource: 0,
    aoe: '4m radius',
    description:
      'You fire the shell at the designated area to summon the turret',
    type: 'Summon',
    usage: 'Skill tap to specify the target location → Skill tap',
    details: [
      'You fire at the designated location, inflicting 132 physical damage to 5 targets maximum in the 4m radius and summon the turret, existing for 15 seconds',
      'Turret fires at targets in the are with shells, each inflicting 30 physical damage',
      'Turret inherits level and stats of the caster',
      'The turret’s area of fire is indicated with a wide circle on video-preview',
      'It is not clarified in the Skill Type section, but the skill is also considered as AOE range attack',
    ],
    mechanics: [],
  },
  {
    beid: '128',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Landmine',
    dmgtype: 'physical',
    dps: [342],
    range: 2,
    cooldown: 20,
    resource: -50,
    aoe: '3m radius',
    description:
      'You install landmine before you. The mine explodes when enemies approach',
    type: 'Summon',
    usage: 'Skill tap',
    details: [
      'The landmine installed exists for 30 seconds',
      'Enemies approaching the vicinity trigger the mine. The blast inflicts 137 physical damage and control Airborne to 5 targets maximum',
    ],
    mechanics: ['airborne'],
  },
  {
    beid: '129',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Aimed Shot',
    dmgtype: 'lightning',
    dps: [100],
    range: 18,
    cooldown: 15,
    resource: -30,
    aoe: 'target',
    description: 'You specify targets to fire special electric rounds',
    type: 'Dual Pistols, Target Projectile',
    usage: 'Skill tap → Aim maintaining → Skill tap',
    details: [
      'You choose 5 target to fire shot, inflicting 35 lightning damage and debuff Electrocute for 8 seconds',
      'Electrocute : Any damage taken by the target additionally inflicts 30 lightning damage',
      'The Skill inflicts 20% more damage to targets with debuff Freezing',
    ],
    mechanics: ['electrocute'],
  },
  {
    beid: '130',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Homing Missiles',
    dmgtype: 'physical',
    dps: [218],
    range: 24,
    cooldown: 20,
    resource: -50,
    aoe: 'target',
    description:
      'You specify targets to launch guided missiles using your rifle',
    type: 'Rifle, Target Projectile',
    usage: 'Skill tap → Aim maintaining → Skill tap',
    details: [
      'You choose 5 targets maximum and launch missiles, each inflicts 3 hits 80 physical damage each',
      'Damage does not disperse while hitting multiple targets',
    ],
    mechanics: [],
  },
  {
    beid: '131',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Volley',
    dmgtype: 'physical',
    dps: [173],
    range: 18,
    cooldown: 28,
    resource: 0,
    aoe: '1m radius',
    description:
      'You jump in the air to fire fast volley of bullets using both of your dual pistols',
    type: 'Dual Pistols, Target Projectile',
    usage: 'Crosshair aiming → Aim maintaining → Skill tap',
    details: [
      'You fire both your pistols at target, inflicting 5 hits 35 physical damage each',
      'The last shot is produced with your rifle, inflicting 200 physical damage and control Knockback to 5 targets maximum in 1m radius',
      'During the cast you acquire effect Dodge',
    ],
    mechanics: ['knockback', 'dodge'],
  },
  {
    beid: '132',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Bomb',
    dmgtype: 'physical',
    dps: [68],
    range: 18,
    cooldown: 12,
    resource: -40,
    aoe: 'target',
    description: 'You load your rifle with the special round with time bomb',
    type: 'Rifle, Target Projectile',
    usage: 'Crosshair aiming → Skill tap',
    details: [
      'You fire a bomb, inflicting target with it for 3 seconds',
      'For 3 seconds target is inflicted with Debuff Incoming Damage Increased by 15%. After 3 seconds bomb explodes, inflicting 206 physical damage to 5 targets maximum in 2m radius',
    ],
    mechanics: ['debuff incoming damage increased'],
  },
  {
    beid: '133',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Scorched Lands',
    dmgtype: 'physical',
    dps: [244, 248],
    range: 18,
    cooldown: 18,
    resource: -60,
    aoe: '10m radius',
    description:
      'You fire 2 shots with both your pistols, first in frontal cone and then around yourself',
    type: 'Dual Pistols, AOE Attack',
    usage: 'Directional aim → Skill tap (2 skills in combo)',
    details: [
      'The first skill in combo inflicts 4 hits 48 physical damage and control Stagger each in frontal cone to 7 targets maximum',
      'The second skill in combo inflicts 4 hits 58 physical damage and control Stagger each in 10m radius to 7 targets maximum',
    ],
    mechanics: ['stagger'],
  },
  {
    beid: '134',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Steel Hailstorm',
    dmgtype: 'physical',
    dps: [67],
    range: 21,
    cooldown: 21,
    resource: -60,
    aoe: '6m radius',
    description:
      'You fire your rifle with small fragmentation shell, which explodes in the air, creating an area of steel fragments raining',
    type: 'Rifle, AOE attack',
    usage: 'Skill tap → Area designation → Skill tap',
    details: [
      'The area produced inflicts 67 physical damage each second for 6 seconds to 7 targets maximum',
      'All targets in the area are inflicted with debuff Slow by 80%',
    ],
    mechanics: ['slow'],
  },
  {
    beid: '135',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Explosive Leap',
    dmgtype: 'physical',
    dps: [190],
    range: 20,
    cooldown: 30,
    resource: 100,
    aoe: '2m radius',
    description:
      'You fire your rifle with an explosive round, creating a blast which allows you to perform a long jump',
    type: 'Rifle, Melee Attack',
    usage: 'Directional aim → Skill tap',
    details: [
      'You perform a 20m leap',
      'ou are cleansed from all of the control. During the leap you acquire effect Dodge',
      'Initial blast inflicts 197 physical damage in 2m radius to 5 targets maximum',
    ],
    mechanics: ['dodge'],
  },
  {
    beid: '136',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Kick',
    dmgtype: 'physical',
    dps: [160, 193],
    range: 10,
    cooldown: 10,
    resource: 10,
    aoe: '2x2m',
    description: 'You perform a charge to kick your enemies',
    type: 'Melee Attack',
    usage: 'Directional aim → Skill tap (2 skills in combo)',
    details: [
      'The first skill in combo: You perform a 10m forward charge, inflicting 59 physical damage and control Stagger to 5 targets maximum',
      'The second skill in combo:  You perform a 4m forward charge, inflicting 4 hits 29 physical damage and control Knockback each for 5 targets maximum',
    ],
    mechanics: ['stagger', 'knockback'],
  },
  {
    beid: '137',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Grenade',
    dmgtype: 'physical',
    dps: [140],
    range: 18,
    cooldown: 10,
    resource: 0,
    aoe: '3m radius',
    description: 'You throw a grenade at a designated trajectory',
    type: 'Non-Piercing Projectile',
    usage: 'Directional aim → Skill tap',
    details: [
      'You throw a grenade, which inflicts 56 physical damage and debuff Stun for 2 seconds in 3m radius to 5 targets maximum',
    ],
    mechanics: ['stun'],
  },
  {
    beid: '138',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Lasso',
    dmgtype: 'physical',
    dps: [150],
    range: 20,
    cooldown: 10,
    resource: 0,
    aoe: '1m radius',
    description: 'You perform a backflip and fire a lasso',
    type: 'Non-Piercing Projectile',
    usage: 'Directional aim → Skill tap',
    details: [
      'You perform backflip, acquiring effect Dodge during the cast',
      'At the same time you fire a lasso, inflicting 98 physical damage and debuff Root for 4 seconds in 1m radius to 5 targets maximum',
      'Root: cannot move or rotate the character',
    ],
    mechanics: ['dodge', 'root'],
  },
  {
    beid: '139',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Suppressive Discharge',
    dmgtype: 'physical',
    dps: [166],
    range: 18,
    cooldown: 24,
    resource: -40,
    aoe: '2x18m',
    description:
      'You charge your rifle with special blast, which fire on a straight line',
    type: 'Rifle, Piercing Projectile',
    usage: 'Trajectory aim → Skill tap',
    details: [
      'Skill inflicts 300 physical damage and control Knockdown to 7 targets maximum',
      'While affected by the buff [Main Caliber] the skill [Suppression Discharge] is casted instantly',
    ],
    mechanics: ['knockdown'],
  },
  {
    beid: '140',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Salvo',
    dmgtype: 'physical',
    dps: [207, 220, 253],
    range: 18,
    cooldown: 12,
    resource: -60,
    aoe: '1.2x18m',
    description:
      'You fire powerful piercing bullets using both of your pistols',
    type: 'Dual Pistols, Piercing Projectile',
    usage: 'Trajectory aim → Skill tap (3 skills in combo)',
    details: [
      'The first skill inflicts 114 physical damage and control Stagger to 7 targets maximum',
      'The second skill inflicts 132 physical damage and control Stagger to 7 targets maximum',
      'The third skill inflicts 253 physical damage and control Stagger to 7 targets maximum',
    ],
    mechanics: ['stagger'],
  },
  {
    beid: '141',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Plasma Globe',
    dmgtype: 'lightning',
    dps: [253],
    range: 18,
    cooldown: 15,
    resource: -40,
    aoe: '1.5m radius',
    description:
      'Using your rifle you fire a 5f9f3adcd706d724a4ecc093 flying plasma globe, which moves in a straight line',
    type: 'Rifle, Piercing Projectile',
    usage: 'Trajectory aim → Skill tap',
    details: [
      'he orb can inflict 35 hits total. Each hit inflicts 29 lightning damage and control Knockback to 5 targets maximum',
      'Damage does not disperse while hitting multiple targets',
      'The Skill inflicts 20% more damage to targets with debuff Freezing',
    ],
    mechanics: ['knockback'],
  },
  {
    beid: '142',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Snipe',
    dmgtype: 'physical',
    dps: [250],
    range: 18,
    cooldown: 0,
    resource: -60,
    aoe: '0.6m radius',
    description: 'You use the laser tag to perform snipe with you rifle',
    type: 'Rifle, Piercing Projectile',
    usage: 'Trajectory aim → Skill tap',
    details: [
      'You perform a snipe with piercing bullet, inflicting 400 physical damage to 7 targets maximum',
      'Damage does not disperse while hitting multiple targets',
      'While affected by the buff [Main Caliber] the skill [Snipe] is casted instantly',
    ],
    mechanics: [],
  },
  {
    beid: '143',
    archetype: '5fa9c171ff89b52f1c809c1d',
    name: 'Plasma Wave',
    dmgtype: 'lightning',
    dps: [97, -291],
    range: 18,
    cooldown: 14,
    resource: -50,
    aoe: '1x18m',
    description: 'You charge your pistols to release 3 energy waves',
    type: 'Dual Pistols, Piercing Projectile',
    usage: 'Skill hold → Aiming',
    details: [
      'You release 3 waves each on 3 colliding directions',
      'Each wave inflicts 124 lightning magic to 7 targets maximum',
      'Targets affected by all 3 waves are inflicted with debuff Stun for 3 seconds',
      'The Skill inflicts 20% more damage to targets with debuff Freezing',
    ],
    mechanics: ['stun'],
  },
];
