export const ARCH_SKILLS_LIST_REQUEST = 'ARCH_SKILLS_LIST_REQUEST';
export const ARCH_SKILLS_LIST_SUCCESS = 'ARCH_SKILLS_LIST_SUCCESS';
export const ARCH_SKILLS_LIST_FAIL = 'ARCH_SKILLS_LIST_FAIL';

export const MECHANICS_LIST_REQUEST = 'MECHANICS_LIST_REQUEST';
export const MECHANICS_LIST_SUCCESS = 'MECHANICS_LIST_SUCCESS';
export const MECHANICS_LIST_FAIL = 'MECHANICS_LIST_FAIL';

export const RUNESTONES_LIST_REQUEST = 'RUNESTONES_LIST_REQUEST';
export const RUNESTONES_LIST_SUCCESS = 'RUNESTONES_LIST_SUCCESS';
export const RUNESTONES_LIST_FAIL = 'RUNESTONES_LIST_FAIL';

export const RUNETRAITS_LIST_REQUEST = 'RUNETRAITS_LIST_REQUEST';
export const RUNETRAITS_LIST_SUCCESS = 'RUNETRAITS_LIST_SUCCESS';
export const RUNETRAITS_LIST_FAIL = 'RUNETRAITS_LIST_FAIL';

export const RUNETRAITS_DETAILS_REQUEST = 'RUNETRAITS_DETAILS_REQUEST';
export const RUNETRAITS_DETAILS_SUCCESS = 'RUNETRAITS_DETAILS_SUCCESS';
export const RUNETRAITS_DETAILS_FAIL = 'RUNETRAITS_DETAILS_FAIL';

export const SEPHIROT_LIST_REQUEST = 'SEPHIROT_LIST_REQUEST';
export const SEPHIROT_LIST_SUCCESS = 'SEPHIROT_LIST_SUCCESS';
export const SEPHIROT_LIST_FAIL = 'SEPHIROT_LIST_FAIL';

export const ARCH_SKILLS_DETAILS_REQUEST = 'ARCH_SKILLS_DETAILS_REQUEST';
export const ARCH_SKILLS_DETAILS_SUCCESS = 'ARCH_SKILLS_DETAILS_SUCCESS';
export const ARCH_SKILLS_DETAILS_FAIL = 'ARCH_SKILLS_DETAILS_FAIL';

export const ARCH_SKILL_DETAILS_REQUEST = 'ARCH_SKILL_DETAILS_REQUEST';
export const ARCH_SKILL_DETAILS_SUCCESS = 'ARCH_SKILL_DETAILS_SUCCESS';
export const ARCH_SKILL_DETAILS_FAIL = 'ARCH_SKILL_DETAILS_FAIL';

export const SKILL_DETAILS_REQUEST = 'SKILL_DETAILS_REQUEST';
export const SKILL_DETAILS_SUCCESS = 'SKILL_DETAILS_SUCCESS';
export const SKILL_DETAILS_FAIL = 'SKILL_DETAILS_FAIL';
